In [27]:
import pandas as pd
from config import *

In [28]:
# read the dataset 

df = pd.read_csv(f'{DATASET_DIR}/dataset.csv')
df.head(3)

,id,image_path,category,question,correct_answer,positive_hint,negative_hint,task_category,answer_data_type,format,source_file
0,1,VisDefAn_hidden_000001.png,camouflaged,Is there an animal camouflaged among the trees?,Yes,The animal has climbed on the top of tree\nbranch,Only trees and leaves can be seen,Adversarial,Binary,Format: [yes/no],camouflaged.json
1,2,VisDefAn_hidden_000001.png,camouflaged,What animal is hiding behind the leaves?,Jaguar,Jaguar can climb the tree,I can see a dog in the image,Object,String,Format: [animal],camouflaged.json
2,3,VisDefAn_hidden_000001.png,camouflaged,Is this a desert?,No,The environment is full of trees and\nanimals,There is no water can be seen in the place,Adversarial,Binary,Format: [yes/no],camouflaged.json

In [29]:
df.shape

(1426, 11)

In [30]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1426 entries, 0 to 1425
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   id                1426 non-null   int64
 1   image_path        1426 non-null   str
 2   category          1426 non-null   str
 3   question          1426 non-null   str
 4   correct_answer    1426 non-null   str
 5   positive_hint     1426 non-null   str
 6   negative_hint     1426 non-null   str
 7   task_category     1426 non-null   str
 8   answer_data_type  1425 non-null   str
 9   format            1408 non-null   str
 10  source_file       1426 non-null   str
dtypes: int64(1), str(10)
memory usage: 122.7 KB

In [31]:
df.isna().sum()

id                   0
image_path           0
category             0
question             0
correct_answer       0
positive_hint        0
negative_hint        0
task_category        0
answer_data_type     1
format              18
source_file          0
dtype: int64

In [32]:
# drop the column format which contain NaN
df = df.dropna(subset=['format', 'answer_data_type'])

In [33]:
df.isna().sum()

id                  0
image_path          0
category            0
question            0
correct_answer      0
positive_hint       0
negative_hint       0
task_category       0
answer_data_type    0
format              0
source_file         0
dtype: int64

In [ ]:
# changing the general into re_used and self-captured as self_captured
df['category'] = df['category'].replace({
    'general': 're_used',           
    'self-captured': 'self_captured' 
})

In [42]:
df.to_csv(f'{DATASET_DIR}/dataset_clean.csv', index=False)

In [ ]:
# changing the general into re_used and self-captured as self_captured

In [39]:
# testing extra

df[df['category'] == 'puzzle'].head(1)

,id,image_path,category,question,correct_answer,positive_hint,negative_hint,task_category,answer_data_type,format,source_file
486,0,image_5.png,puzzle,What is the parking space number beneath the car?,87,The parking number is 87,The parking number is 78,puzzle,number,[number],puzzle.json

In [40]:
df['category'].unique()

<StringArray>
[          'camouflaged', 'confusing_perspective',                   'OCR',
                'puzzle',               'general',         'self-captured']
Length: 6, dtype: str